### ISSUE TITLE
[Grade Predictor] Too small grades generated for etalon activity during trimester.

### ISSUE THREAD

**Issue by danorel** [oletsky/superavtomat#1]
https://github.com/oletsky/superavtomat/blob/aaaaaab21b535dda4c6e3ca8c36da1163c269603/predict.js#L10-L16

Hi! 

I have checked up your code and the algorithm for grade prediction, and I believe, that your algorithm should be improved in some way...

```
"kappa": 0.7
"cremain": 0.4
"ckarma": 0.6

let remain = (v2 == -1) ? 40 : 10;
if (v2 == -1) v2 = 0;
let v = v1 + v2;
let ratio=v/maxim;

let coeff=cRemain*ratio+cKarma*karma*0.01;
let r = v + remain*coeff * kappa; 
```

Your algorithm calculates if etalon student has maximum grade (55) during the whole semester and with maximum karma (1), he will receive such grade: 
```r = (55 + 0) + 40 * (0.4 * 1 + 0.6 * 100 * 0.01) * 0.7 = 55 + 28 ~ 83 score.```

In my case, I have:
``` r = (37 + 0) + 40 * (0.4 * 1 + 0.6 * 95 * 0.01) * 0.7 ~ 64 score, as I heard.```

Is it possible to correct the algorithm, because students with maximum activity and maximum score during the trimester receive low score in result?

I think, that correcting the "kappa" rate from 0.7 to 1 can improve the situation in some way, 
Thanks!

**Comment by Setteren** [comment]
just WOW

**Comment by oletsky** [comment]
If maximum is 55 than the remainder is 45, not 40, It gives 86, not 83. This has been taken into account.

There is no reason to increase kappa. It a student thinks that they deserve more they can pass the exam. If results are really impeccaple 92 may be suggested, but your grades are  not so excellent at the moment. Why don't you contact your instructor directly? You still might make your best to improve your current result.

Sincerely yours,

Malicious Dev

**Comment by danorel** [comment]
Thanks for your detailed explanation about the system of grade generation. 

I did not really care about my grade on this course, but in general how the algorithm works.

The main reason why I had opened the issue is the fair estimation of student's activity during the course on 100 points scale. I have understood that students, which would like to take the automatic generated grade have a chance to receive a maximum of 92 points. It wasn't really clear to me why not 100.

But at the same time, if you will re-view this algorithm and transform it to a 100-points scale, it would be a great opportunity for students to increase the points they receive due to their thorough work during the course.

Sincerely yours,
Fighter for justice.

**Comment by oletsky** [comment]
Well, it's not 100 but maximum 92 because it is going to happen without a test, exam, etc. In addition, a control on checking tasks is not very rigorous, and mistakes may happen. Nothing unfair. A student has full rights to reject such a proposal and to sit their exam. Automatical grading is not something granted at all, it is a question of a good will and that of mutual consent. If something is wrong it's not late to revoke all the matter at all, but you remember this was initiated just by the students. Really, usually automatical generated grades are noticeably lower that the actual level which migth be shown at the exam, but students have all chances to show this level. But on the other hand, exceptions happen as well.


> Thanks for your detailed explanation about the system of grade generation.
> 
> I did not really care about my grade on this course, but in general how the algorithm works.
> 
> The main reason why I had opened the issue is the fair estimation of student's activity during the course on 100 points scale. I have understood that students, which would like to take the automatic generated grade have a chance to receive a maximum of 92 points. It wasn't really clear to me why not 100.
> 
> But at the same time, if you will re-view this algorithm and transform it to a 100-points scale, it would be a great opportunity for students to increase the points they receive due to their thorough work during the course.
> 
> Sincerely yours,
> Fighter for justice.

**Comment by danorel** [comment]
Thanks for your great explanation!
This became more clear for me.

Have a nice evening :3
